# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44321b4542d79de1bc738bd90c96c80ad4328afb61e7d969d6b947d88b9b7183a64e6863a571f49fd1637508192779a0425f33e0234051c4235b677725cdd958

test:
  secret_key_base: 4af54562e75a715960a134ed555b5f876eaa8f0400dc99835bdae1d5bfd227e586dcd144ec2b1933789b5798de3941e4d459f3ef3dc8f2dc6bd2bd20afefa5af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
